import Head from "next/head";

import Header from "./Header";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gray500">
        <Header />
        {children}
      </main>
    </>
  );
}

export default Layout;
