import Head from "next/head";

import Header from "./Header";
import Alert from "./Alert";
import Image from "next/image";

function Layout({ children }) {
  return (
    <>
      <Head>
        <title>TODO App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="h-screen bg-gray400">
        <Header />
        <Alert>
          <Image
            src={"/image/icon-alert-circle.svg"}
            alt="icon-alert-circle"
            width={24}
            height={24}
            className="mr-[10px]"
          />
          <p>Activity berhasil dihapus</p>
        </Alert>
        {children}
      </main>
    </>
  );
}

export default Layout;
